const defaultData = [
  {
    github_id: 'gcnit',
    id: 'gcnit',
    linkedin_id: 'gcnit',
    codechef_id: 'gc_nit',
    twitter_id: 'gc_nit',
    medium_id: 'gc_nit',
    avatar_url: 'https://avatars.githubusercontent.com/u/4833751?v=4',
    name: 'Gaurav Chandak',
    company: 'workat.tech',
    blog: 'https://workat.tech',
    location: 'Bangalore, India',
    email: null,
    bio: 'Building workat.tech;\r\n' + 'Previously Software Engineer at  @Flipkart, @microsoft and @tracxn',
    repos: [
      {
        name: 'awesome-learn-to-code',
        html_url: 'https://github.com/gcnit',
        description: 'A list of awesome resources for learning to code',
        updated_at: '2021-03-11T04:24:18Z',
      },
      {
        name: 'beta.sdeskills.com',
        html_url: 'https://github.com/gcnit',
        description: 'Beta SDE Skills site',
        updated_at: '2020-06-08T08:19:59Z',
      },
      {
        name: 'Birthdpy',
        html_url: 'https://github.com/gcnit',
        description: 'This script thanks everyone who have wished you on your birthday on your facebook timeline',
        updated_at: '2017-10-11T04:05:01Z',
      },
      {
        name: 'code-template',
        html_url: 'https://github.com/gcnit',
        description: null,
        updated_at: '2021-05-07T12:07:18Z',
      },
      {
        name: 'Comment-Liker',
        html_url: 'https://github.com/gcnit',
        description:
          'Placed? Everyone congratulating you on your status update? Like all their comments automatically with this script!',
        updated_at: '2014-10-25T19:41:51Z',
      },
      {
        name: 'Competitive-Programming',
        html_url: 'https://github.com/gcnit',
        description: 'My solutions to algorithmic problems on Competitive Programming websites',
        updated_at: '2020-12-19T15:23:40Z',
      },
      {
        name: 'Competitive-Programming-Resources',
        html_url: 'https://github.com/gcnit',
        description: 'Competitive Programming & System Design Resources.',
        updated_at: '2021-05-23T13:45:33Z',
      },
      {
        name: 'conclave',
        html_url: 'https://github.com/gcnit',
        description: 'CRDT and WebRTC based real-time, peer-to-peer, collaborative text editor',
        updated_at: '2020-04-07T18:40:56Z',
      },
      {
        name: 'design-patterns-for-humans',
        html_url: 'https://github.com/gcnit',
        description: 'An ultra-simplified explanation to design patterns',
        updated_at: '2019-09-05T16:46:52Z',
      },
      {
        name: 'Design-Patterns-Implementation',
        html_url: 'https://github.com/gcnit',
        description: 'Implementations of Common Design Patterns',
        updated_at: '2017-11-26T07:35:43Z',
      },
      {
        name: 'developer-roadmap',
        html_url: 'https://github.com/gcnit',
        description: 'Roadmap to becoming a web developer in 2018',
        updated_at: '2019-01-30T06:24:48Z',
      },
      {
        name: 'gcnit',
        html_url: 'https://github.com/gcnit',
        description: null,
        updated_at: '2020-08-15T20:31:18Z',
      },
      {
        name: 'gcnit.github.io',
        html_url: 'https://github.com/gcnit',
        description: null,
        updated_at: '2019-11-12T16:52:28Z',
      },
      {
        name: 'get-a-software-engineering-job',
        html_url: 'https://github.com/gcnit',
        description: 'Get a Software Engineering Job - Ultimate Guide',
        updated_at: '2020-08-16T10:53:19Z',
      },
      {
        name: 'Implementations',
        html_url: 'https://github.com/gcnit',
        description: null,
        updated_at: '2017-11-22T17:36:47Z',
      },
      {
        name: 'learn-to-program',
        html_url: 'https://github.com/gcnit',
        description: 'Educational resources to learn to program (Foundation in Web Development)',
        updated_at: '2020-08-12T18:28:02Z',
      },
      {
        name: 'learn_to_code',
        html_url: 'https://github.com/gcnit',
        description: 'Resources for budding developers',
        updated_at: '2020-08-12T18:30:07Z',
      },
      {
        name: 'Like-All-Posts',
        html_url: 'https://github.com/gcnit',
        description: 'This script likes all the posts made by an user or a page on their facebook timeline',
        updated_at: '2016-08-07T05:48:03Z',
      },
      {
        name: 'low-level-design',
        html_url: 'https://github.com/gcnit',
        description: 'This repository contains some programs for learning OOD using c++',
        updated_at: '2021-06-04T18:01:24Z',
      },
      {
        name: 'low-level-design-primer',
        html_url: 'https://github.com/gcnit',
        description:
          'Dedicated Resources for the Low-Level System Design. Learn how to design and implement large-scale systems. Prep for the system design interview.',
        updated_at: '2021-04-27T19:44:55Z',
      },
      {
        name: 'machinecoding',
        html_url: 'https://github.com/gcnit',
        description: 'Everything about Machine Coding Round',
        updated_at: '2020-03-03T18:31:32Z',
      },
      {
        name: 'mediumish-minimal',
        html_url: 'https://github.com/gcnit',
        description: null,
        updated_at: '2020-03-08T12:34:41Z',
      },
      {
        name: 'mentorship-karona',
        html_url: 'https://github.com/gcnit',
        description: 'If you need a session with mentors raise an issue',
        updated_at: '2020-08-31T21:28:33Z',
      },
      {
        name: 'Mind-Expanding-Books',
        html_url: 'https://github.com/gcnit',
        description: ' :books: Books that will blow your mind ',
        updated_at: '2019-01-30T06:24:59Z',
      },
      {
        name: 'mock-machine-coding-1',
        html_url: 'https://github.com/gcnit',
        description: null,
        updated_at: '2021-05-30T13:10:49Z',
      },
      {
        name: 'NITMDb',
        html_url: 'https://github.com/gcnit',
        description: 'A script that helps you get your movie collection sorted based on their IMDb ratings',
        updated_at: '2018-05-26T09:25:37Z',
      },
      {
        name: 'pdfkit-invoice',
        html_url: 'https://github.com/gcnit',
        description: 'Generate PDF Invoices with PDFKit',
        updated_at: '2020-08-14T11:02:56Z',
      },
      {
        name: 'problemsolving',
        html_url: 'https://github.com/gcnit',
        description: 'Everything about the Problem Solving & Data Structures Round',
        updated_at: '2020-03-12T20:49:45Z',
      },
      {
        name: 'product-search',
        html_url: 'https://github.com/gcnit',
        description: null,
        updated_at: '2020-02-02T08:52:35Z',
      },
      {
        name: 'programming-principles',
        html_url: 'https://github.com/gcnit',
        description: 'Categorized overview of Programming Principles & Patterns',
        updated_at: '2019-01-30T06:24:57Z',
      },
    ],
  },
  {
    id: 'sagar0907',
    linkedin_id: 'sagarjain0907',
    codechef_id: '',
    hackerrank_id: '',
    twitter_id: '',
    medium_id: '',
    avatar_url: 'https://avatars.githubusercontent.com/u/8445055?v=4',
    name: 'Sagar Jain',
    company: '@workattech',
    blog: 'https://workat.tech',
    location: 'Bangalore',
    email: null,
    bio: 'Building workat.tech; Previously Software Engineer at @uber and @media-net',
    github_id: 'sagar0907',
    repos: [
      {
        name: 'bringe',
        html_url: 'https://github.com/sagar0907',
        description: 'Chrome Extension for virtually everything related to movies and tv series',
        updated_at: '2019-08-16T11:46:56Z',
      },
      {
        name: 'copycat',
        html_url: 'https://github.com/sagar0907',
        description:
          'Chrome extension which stores and helps you manage everything you copy on web pages, so that you can access them later.',
        updated_at: '2018-09-27T18:53:53Z',
      },
      {
        name: 'firepad',
        html_url: 'https://github.com/sagar0907',
        description: 'Collaborative text editing powered by Firebase',
        updated_at: '2021-10-14T10:52:38Z',
      },
      {
        name: 'quickNotes',
        html_url: 'https://github.com/sagar0907',
        description: 'Chrome extension to make and access notes quickly, at the launch of a new tab.',
        updated_at: '2021-01-03T20:52:52Z',
      },
      {
        name: 'RECursionWebsite',
        html_url: 'https://github.com/sagar0907',
        description: null,
        updated_at: '2016-07-27T18:10:39Z',
      },
      {
        name: 'sagar0907.github.io',
        html_url: 'https://github.com/sagar0907',
        description: null,
        updated_at: '2020-06-24T19:23:24Z',
      },
      {
        name: 'webscout',
        html_url: 'https://github.com/sagar0907',
        description:
          'Search everything, everywhere. A chrome extension which takes over your new tab so that searching your favourite websites become a lot easier.',
        updated_at: '2018-08-27T15:17:40Z',
      },
    ],
  },
  {
    github_id: 'sumedha1308',
    id: 'sumedha1308',
    linkedin_id: 'sumedha1308',
    codechef_id: '',
    twitter_id: 'SUMEDHADESHPAN1',
    medium_id: '',
    avatar_url: 'https://avatars.githubusercontent.com/u/25945916?v=4',
    name: 'Sumedha Deshpande',
    company: 'BMC Software',
    blog: '',
    location: 'Pune, India',
    email: null,
    bio: 'Associate Product Developer at BMC Software',
    repos: [
      {
        name: 'dev-profile',
        html_url: 'https://github.com/sumedha1308/dev-profile',
        description:
          'Developer profile is an ERN(Express, React, Node) web application developed from UI design, where user can easily create their developer profile for storing multiple profile links of a developer in a single shareable page.',
        updated_at: '2022-01-17T17:42:54Z',
      },
      {
        name: 'Sumedha-Portfolio',
        html_url: 'https://github.com/sumedha1308/Sumedha-Portfolio',
        description: 'Created portfolio is to showcase and share my knowledge, experience, developed projects.',
        updated_at: '2022-01-15T15:55:18Z',
      },
      {
        name: 'MathQuiz',
        html_url: 'https://github.com/sumedha1308/MathQuiz',
        description: null,
        updated_at: '2021-05-03T15:40:20Z',
      },
      {
        name: 'url-shortener',
        html_url: 'https://github.com/sumedha1308/url-shortener',
        description:
          'URL shortener creates a short, secure, unique URL from Long URL.URL shortener will save user’s time in shortening same URL again as recent 5 URLs are available for short time temporarily.',
        updated_at: '2022-01-14T17:17:23Z',
      },
    ],
  },
];
module.exports = defaultData;
